add working inference example

diff --git a/examples/sagemaker-tensorflow/container/serve b/examples/sagemaker-tensorflow/container/serve
--- a/examples/sagemaker-tensorflow/container/serve
+++ b/examples/sagemaker-tensorflow/container/serve
@@ -87,23 +87,23 @@ if [ "${is_mme_mode}" = false ] && [ -n "$SAGEMAKER_TRITON_DEFAULT_MODEL_NAME" ]
         echo "ERROR: Directory with provided SAGEMAKER_TRITON_DEFAULT_MODEL_NAME ${SAGEMAKER_TRITON_DEFAULT_MODEL_NAME} does not exist"
         exit 1
     fi
-# elif [ "${is_mme_mode}" = false ]; then
-#     MODEL_DIRS=(`find "${SAGEMAKER_MODEL_REPO}" -mindepth 1 -maxdepth 1 -type d -printf "%f\n"`)
-#     case ${#MODEL_DIRS[@]} in
-#         0) echo "ERROR: No model found in model repository";
-#            exit 1
-#            ;;
-#         1) echo "WARNING: No SAGEMAKER_TRITON_DEFAULT_MODEL_NAME provided."
-#            echo "         Starting with the only existing model directory ${MODEL_DIRS[0]}";
-#            export SAGEMAKER_TRITON_DEFAULT_MODEL_NAME=${MODEL_DIRS[0]}
-#            ;;
-#         *) echo "ERROR: More than 1 model directory found in model repository."
-#            echo "       Either provide a single directory or set SAGEMAKER_TRITON_DEFAULT_MODEL_NAME to run the ensemble backend."
-#            echo "       Directories found in model repository: ${MODEL_DIRS[@]}";
-#            exit 1
-#            ;;
-#     esac
-#     SAGEMAKER_ARGS="${SAGEMAKER_ARGS} --load-model=${SAGEMAKER_TRITON_DEFAULT_MODEL_NAME}"
+#elif [ "${is_mme_mode}" = false ]; then
+#    MODEL_DIRS=(`find "${SAGEMAKER_MODEL_REPO}" -mindepth 1 -maxdepth 1 -type d -printf "%f\n"`)
+#    case ${#MODEL_DIRS[@]} in
+#        0) echo "ERROR: No model found in model repository";
+#           exit 1
+#           ;;
+#        1) echo "WARNING: No SAGEMAKER_TRITON_DEFAULT_MODEL_NAME provided."
+#           echo "         Starting with the only existing model directory ${MODEL_DIRS[0]}";
+#           export SAGEMAKER_TRITON_DEFAULT_MODEL_NAME=${MODEL_DIRS[0]}
+#           ;;
+#        *) echo "ERROR: More than 1 model directory found in model repository."
+#           echo "       Either provide a single directory or set SAGEMAKER_TRITON_DEFAULT_MODEL_NAME to run the ensemble backend."
+#           echo "       Directories found in model repository: ${MODEL_DIRS[@]}";
+#           exit 1
+#           ;;
+#    esac
+    SAGEMAKER_ARGS="${SAGEMAKER_ARGS} --load-model=${SAGEMAKER_TRITON_DEFAULT_MODEL_NAME}"
 fi
 
 tritonserver --allow-sagemaker=true --allow-grpc=false --allow-http=false --allow-metrics=false --model-control-mode=explicit $SAGEMAKER_ARGS
